/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp_poo.IHM;

import com.mycompany.tp_poo.core.Agent;
import com.mycompany.tp_poo.core.Contact;
import com.mycompany.tp_poo.core.Enseignant;
import com.mycompany.tp_poo.core.Etudiant;
import com.mycompany.tp_poo.core.Repertoire;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class CreerUnContact extends javax.swing.JFrame {
    Repertoire repertoire;
    Frame parent;
    /**
     * Creates new form CreerUnContact
     */
    public CreerUnContact(Repertoire reper, Frame jf) {
        this.repertoire = reper;
        this.parent = jf;
        
        initComponents();
        this.choixComboBoxActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creerUnEtudiantPanel = new javax.swing.JPanel();
        nomFieldEtudiant = new javax.swing.JTextField();
        adressFieldEtudiant = new javax.swing.JTextField();
        emailFieldEtudiant = new javax.swing.JTextField();
        numeroFieldEtudiant = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        codeFieldEtudiant = new javax.swing.JTextField();
        dateNaissanceFieldEtudiant = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cycleFieldComboBoxEtudiant = new javax.swing.JComboBox<>();
        niveauFieldComboBoxEtudiant = new javax.swing.JComboBox<>();
        creerUnEnseignantPanel = new javax.swing.JPanel();
        nomFieldEnseignant = new javax.swing.JTextField();
        dateNaissanceFieldEnseignant = new javax.swing.JTextField();
        adressFieldEnseignant = new javax.swing.JTextField();
        emailFieldEnseignant = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        numeroFieldEnseignant = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        codeFieldEnseignant = new javax.swing.JTextField();
        statutFieldComboBoxEnseignant = new javax.swing.JComboBox<>();
        creerUnAgentPanel = new javax.swing.JPanel();
        nomFieldAgent = new javax.swing.JTextField();
        dateNaissanceFieldAgent = new javax.swing.JTextField();
        adressFieldAgent = new javax.swing.JTextField();
        salaireFieldAgent = new javax.swing.JTextField();
        emailFieldAgent = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        numeroFieldAgent = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        codeFieldAgent = new javax.swing.JTextField();
        categorieFieldAgent = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        indiceFieldAgent = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        occupationFieldAgent = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        statutFieldComboBoxAgent = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        enregistrerButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        choixComboBox = new javax.swing.JComboBox<>();
        contentForm = new javax.swing.JPanel();

        nomFieldEtudiant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        nomFieldEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldEtudiantActionPerformed(evt);
            }
        });

        adressFieldEtudiant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        adressFieldEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressFieldEtudiantActionPerformed(evt);
            }
        });

        emailFieldEtudiant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        emailFieldEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldEtudiantActionPerformed(evt);
            }
        });

        numeroFieldEtudiant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        numeroFieldEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFieldEtudiantActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel15.setText("Code :");

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel16.setText("Nom :");

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel17.setText("Date de Naissance :");

        jLabel18.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel18.setText("Adresse :");

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel19.setText("Email :");

        jLabel20.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel20.setText("Numéro Téléphone :");

        codeFieldEtudiant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        codeFieldEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldEtudiantActionPerformed(evt);
            }
        });

        dateNaissanceFieldEtudiant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        dateNaissanceFieldEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNaissanceFieldEtudiantActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel21.setText("Cycle :");

        jLabel22.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel22.setText("Niveau :");

        cycleFieldComboBoxEtudiant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licence", "Ingénieur" }));
        cycleFieldComboBoxEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cycleFieldComboBoxEtudiantActionPerformed(evt);
            }
        });

        niveauFieldComboBoxEtudiant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout creerUnEtudiantPanelLayout = new javax.swing.GroupLayout(creerUnEtudiantPanel);
        creerUnEtudiantPanel.setLayout(creerUnEtudiantPanelLayout);
        creerUnEtudiantPanelLayout.setHorizontalGroup(
            creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creerUnEtudiantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeFieldEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(dateNaissanceFieldEtudiant)
                    .addComponent(nomFieldEtudiant)
                    .addComponent(adressFieldEtudiant)
                    .addComponent(emailFieldEtudiant)
                    .addComponent(numeroFieldEtudiant)
                    .addComponent(cycleFieldComboBoxEtudiant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(niveauFieldComboBoxEtudiant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        creerUnEtudiantPanelLayout.setVerticalGroup(
            creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creerUnEtudiantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeFieldEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomFieldEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNaissanceFieldEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressFieldEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailFieldEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroFieldEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cycleFieldComboBoxEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niveauFieldComboBoxEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomFieldEnseignant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        nomFieldEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldEnseignantActionPerformed(evt);
            }
        });

        dateNaissanceFieldEnseignant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        dateNaissanceFieldEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNaissanceFieldEnseignantActionPerformed(evt);
            }
        });

        adressFieldEnseignant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        adressFieldEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressFieldEnseignantActionPerformed(evt);
            }
        });

        emailFieldEnseignant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        emailFieldEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldEnseignantActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel23.setText("Statut :");

        numeroFieldEnseignant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        numeroFieldEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFieldEnseignantActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel24.setText("Code :");

        jLabel26.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel26.setText("Nom :");

        jLabel27.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel27.setText("Date de Naissance :");

        jLabel28.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel28.setText("Adresse :");

        jLabel29.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel29.setText("Email :");

        jLabel30.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel30.setText("Numéro Téléphone :");

        codeFieldEnseignant.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        codeFieldEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldEnseignantActionPerformed(evt);
            }
        });

        statutFieldComboBoxEnseignant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacataire", "Permanent" }));

        javax.swing.GroupLayout creerUnEnseignantPanelLayout = new javax.swing.GroupLayout(creerUnEnseignantPanel);
        creerUnEnseignantPanel.setLayout(creerUnEnseignantPanelLayout);
        creerUnEnseignantPanelLayout.setHorizontalGroup(
            creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creerUnEnseignantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeFieldEnseignant, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(dateNaissanceFieldEnseignant)
                    .addComponent(nomFieldEnseignant)
                    .addComponent(adressFieldEnseignant)
                    .addComponent(emailFieldEnseignant)
                    .addComponent(numeroFieldEnseignant)
                    .addComponent(statutFieldComboBoxEnseignant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        creerUnEnseignantPanelLayout.setVerticalGroup(
            creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creerUnEnseignantPanelLayout.createSequentialGroup()
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeFieldEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomFieldEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNaissanceFieldEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressFieldEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailFieldEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroFieldEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statutFieldComboBoxEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        nomFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        nomFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldAgentActionPerformed(evt);
            }
        });

        dateNaissanceFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        dateNaissanceFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNaissanceFieldAgentActionPerformed(evt);
            }
        });

        adressFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        adressFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressFieldAgentActionPerformed(evt);
            }
        });

        salaireFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        salaireFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaireFieldAgentActionPerformed(evt);
            }
        });

        emailFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        emailFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldAgentActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel25.setText("Salaire :");

        numeroFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        numeroFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFieldAgentActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel31.setText("Code :");

        jLabel32.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel32.setText("Satut :");

        jLabel33.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel33.setText("Nom :");

        jLabel34.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel34.setText("Date de Naissance :");

        jLabel35.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel35.setText("Adresse :");

        jLabel36.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel36.setText("Email :");

        jLabel37.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel37.setText("Numéro Téléphone :");

        codeFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        codeFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldAgentActionPerformed(evt);
            }
        });

        categorieFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        categorieFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieFieldAgentActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel38.setText("Catégorie");

        indiceFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        indiceFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceFieldAgentActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel39.setText("Indice du salaire:");

        occupationFieldAgent.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        occupationFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationFieldAgentActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel40.setText("Occupation :");

        statutFieldComboBoxAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temporaire", "Stagiaire", "Permanent" }));

        javax.swing.GroupLayout creerUnAgentPanelLayout = new javax.swing.GroupLayout(creerUnAgentPanel);
        creerUnAgentPanel.setLayout(creerUnAgentPanelLayout);
        creerUnAgentPanelLayout.setHorizontalGroup(
            creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creerUnAgentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categorieFieldAgent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codeFieldAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(dateNaissanceFieldAgent)
                    .addComponent(nomFieldAgent)
                    .addComponent(adressFieldAgent)
                    .addComponent(emailFieldAgent)
                    .addComponent(numeroFieldAgent)
                    .addComponent(salaireFieldAgent)
                    .addComponent(indiceFieldAgent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(occupationFieldAgent)
                    .addComponent(statutFieldComboBoxAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        creerUnAgentPanelLayout.setVerticalGroup(
            creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creerUnAgentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNaissanceFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaireFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statutFieldComboBoxAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorieFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indiceFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creerUnAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupationFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Créer un contact");

        enregistrerButton.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        enregistrerButton.setText("Enregistrer");
        enregistrerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        choixComboBox.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        choixComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Enseignant", "Agent" }));
        choixComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentFormLayout = new javax.swing.GroupLayout(contentForm);
        contentForm.setLayout(contentFormLayout);
        contentFormLayout.setHorizontalGroup(
            contentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentFormLayout.setVerticalGroup(
            contentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addComponent(enregistrerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enregistrerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerButtonActionPerformed
        Contact cont;
        boolean stop = true;
        
            try{
            String choix = (String)choixComboBox.getSelectedItem();

            if(choix.equals("Etudiant")){
                cont = new Etudiant();

                SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");

                cont.setAdresse(this.adressFieldEtudiant.getText());
                cont.setCode(this.codeFieldEtudiant.getText());
                cont.setNom(this.nomFieldEtudiant.getText());
                if(cont.getCode().isBlank()|| cont.getNom().isBlank()){
                        JOptionPane.showMessageDialog(null, "Le code et le nom doivent être non null", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                cont.setDateDeNaissance(df.parse(this.dateNaissanceFieldEtudiant.getText()));
                if(cont.getDateDeNaissance() == null ){
                    JOptionPane.showMessageDialog(null, "La date n'est pas dans le bon format\n le bon format est dd-MM-yyyy", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                cont.setEmail(this.emailFieldEtudiant.getText());
                cont.setTelNumber(this.numeroFieldEtudiant.getText());
                ((Etudiant)cont).setCycle((String)(this.cycleFieldComboBoxEtudiant.getSelectedItem()));
                ((Etudiant)cont).setNiveau(this.niveauFieldComboBoxEtudiant.getSelectedIndex()+1);     
            }
            else if(choix.equals("Enseignant")){
                cont  = new Enseignant();

                SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");

                cont.setAdresse(this.adressFieldEnseignant.getText());
                cont.setCode(this.codeFieldEnseignant.getText());
                cont.setNom(this.nomFieldEnseignant.getText());
                if(cont.getCode().isBlank()|| cont.getNom().isBlank()){
                        JOptionPane.showMessageDialog(null, "Le code et le nom doivent être non null", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                cont.setDateDeNaissance(df.parse(this.dateNaissanceFieldEnseignant.getText()));
                if(cont.getDateDeNaissance() == null ){
                    JOptionPane.showMessageDialog(null, "La date n'est pas dans le bon format\n le bon format est dd-MM-yyyy", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                cont.setEmail(this.emailFieldEnseignant.getText());
                cont.setTelNumber(this.numeroFieldEnseignant.getText());
                ((Enseignant)cont).setStatut((String)(this.statutFieldComboBoxEnseignant.getSelectedItem()));
            }
            else{
                cont = new Agent();

                SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");

                cont.setAdresse(this.adressFieldAgent.getText());
                cont.setCode(this.codeFieldAgent.getText());
                cont.setNom(this.nomFieldAgent.getText());
                if(cont.getCode().isBlank()|| cont.getNom().isBlank()){
                        JOptionPane.showMessageDialog(null, "Le code et le nom doivent être non null", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                        return;
                }
                cont.setDateDeNaissance(df.parse(this.dateNaissanceFieldAgent.getText()));
                if(cont.getDateDeNaissance() == null ){
                    JOptionPane.showMessageDialog(null, "La date n'est pas dans le bon format\n le bon format est dd-MM-yyyy", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                }
                cont.setEmail(this.emailFieldAgent.getText());
                cont.setTelNumber(this.numeroFieldAgent.getText());
                ((Agent)cont).setCategorie(this.categorieFieldAgent.getText());
                ((Agent)cont).setIndiceDeSalaire(this.salaireFieldAgent.getText());
                ((Agent)cont).setOccupation(this.occupationFieldAgent.getText());
                ((Agent)cont).setStatut((String)(this.statutFieldComboBoxAgent.getSelectedItem()));
                try{
                    ((Agent)cont).setSalaire(Double.parseDouble(this.salaireFieldAgent.getText()));
                }catch(NumberFormatException e){
                     JOptionPane.showMessageDialog(null, "Veuillez entrer un valeur correcte pour le salaire de l'agent", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                     return;
                }
            }
            this.repertoire.ajouterUnContact(cont);
        
        this.parent.setVisible(true);
        this.setVisible(false);
            
            }catch (ParseException ex) {
                        JOptionPane.showMessageDialog(null, "La date n'est pas dans le bon format\n le bon format est dd-MM-yyyy", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                    return;
            }
            
            
    }//GEN-LAST:event_enregistrerButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nomFieldEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldEtudiantActionPerformed

    private void adressFieldEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressFieldEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressFieldEtudiantActionPerformed

    private void emailFieldEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldEtudiantActionPerformed

    private void numeroFieldEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFieldEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFieldEtudiantActionPerformed

    private void codeFieldEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldEtudiantActionPerformed

    private void dateNaissanceFieldEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNaissanceFieldEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNaissanceFieldEtudiantActionPerformed

    private void nomFieldEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldEnseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldEnseignantActionPerformed

    private void dateNaissanceFieldEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNaissanceFieldEnseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNaissanceFieldEnseignantActionPerformed

    private void adressFieldEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressFieldEnseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressFieldEnseignantActionPerformed

    private void emailFieldEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldEnseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldEnseignantActionPerformed

    private void numeroFieldEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFieldEnseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFieldEnseignantActionPerformed

    private void codeFieldEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldEnseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldEnseignantActionPerformed

    private void nomFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldAgentActionPerformed

    private void dateNaissanceFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNaissanceFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNaissanceFieldAgentActionPerformed

    private void adressFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressFieldAgentActionPerformed

    private void salaireFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaireFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaireFieldAgentActionPerformed

    private void emailFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldAgentActionPerformed

    private void numeroFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFieldAgentActionPerformed

    private void codeFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldAgentActionPerformed

    private void categorieFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorieFieldAgentActionPerformed

    private void indiceFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indiceFieldAgentActionPerformed

    private void occupationFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationFieldAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationFieldAgentActionPerformed

    private void choixComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixComboBoxActionPerformed
        int choix = choixComboBox.getSelectedIndex();
        
        if(choix == 0){
            contentForm.setLayout(new BorderLayout());
            contentForm.removeAll();
            contentForm.repaint();
            contentForm.add(this.creerUnEtudiantPanel);
            contentForm.revalidate();
        }
        else if(choix == 1){
            contentForm.setLayout(new BorderLayout());
            contentForm.removeAll();
            contentForm.repaint();
            contentForm.add(this.creerUnEnseignantPanel);
            contentForm.revalidate();
        }
        else if(choix == 2){
            contentForm.setLayout(new BorderLayout());
            contentForm.removeAll();
            contentForm.repaint();
            contentForm.add(this.creerUnAgentPanel);
            contentForm.revalidate();
        }
    }//GEN-LAST:event_choixComboBoxActionPerformed

    private void cycleFieldComboBoxEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cycleFieldComboBoxEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cycleFieldComboBoxEtudiantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressFieldAgent;
    private javax.swing.JTextField adressFieldEnseignant;
    private javax.swing.JTextField adressFieldEtudiant;
    private javax.swing.JTextField categorieFieldAgent;
    private javax.swing.JComboBox<String> choixComboBox;
    private javax.swing.JTextField codeFieldAgent;
    private javax.swing.JTextField codeFieldEnseignant;
    private javax.swing.JTextField codeFieldEtudiant;
    private javax.swing.JPanel contentForm;
    private javax.swing.JPanel creerUnAgentPanel;
    private javax.swing.JPanel creerUnEnseignantPanel;
    private javax.swing.JPanel creerUnEtudiantPanel;
    private javax.swing.JComboBox<String> cycleFieldComboBoxEtudiant;
    private javax.swing.JTextField dateNaissanceFieldAgent;
    private javax.swing.JTextField dateNaissanceFieldEnseignant;
    private javax.swing.JTextField dateNaissanceFieldEtudiant;
    private javax.swing.JTextField emailFieldAgent;
    private javax.swing.JTextField emailFieldEnseignant;
    private javax.swing.JTextField emailFieldEtudiant;
    private javax.swing.JButton enregistrerButton;
    private javax.swing.JTextField indiceFieldAgent;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JComboBox<String> niveauFieldComboBoxEtudiant;
    private javax.swing.JTextField nomFieldAgent;
    private javax.swing.JTextField nomFieldEnseignant;
    private javax.swing.JTextField nomFieldEtudiant;
    private javax.swing.JTextField numeroFieldAgent;
    private javax.swing.JTextField numeroFieldEnseignant;
    private javax.swing.JTextField numeroFieldEtudiant;
    private javax.swing.JTextField occupationFieldAgent;
    private javax.swing.JTextField salaireFieldAgent;
    private javax.swing.JComboBox<String> statutFieldComboBoxAgent;
    private javax.swing.JComboBox<String> statutFieldComboBoxEnseignant;
    // End of variables declaration//GEN-END:variables
}
