/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp_poo.IHM;

import com.mycompany.tp_poo.core.Agent;
import com.mycompany.tp_poo.core.Contact;
import com.mycompany.tp_poo.core.Enseignant;
import com.mycompany.tp_poo.core.Etudiant;
import com.mycompany.tp_poo.core.Repertoire;
import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class ListeDesContacts extends javax.swing.JFrame {
    Repertoire repertoire;
    Frame parent;
    /**
     * Creates new form ListeDesContacts
     */
    public ListeDesContacts(Repertoire rep, Frame jf) {
        this.repertoire = rep;
        this.parent = jf;
        initComponents();
        
        for(Contact cont : rep.getListeDeContact()){
            if(cont instanceof Etudiant etudiant){
                    String tbData[] = {etudiant.getCode(), etudiant.getNom(), 
                        etudiant.getDateDeNaissance().toString(), etudiant.getAdresse(), 
                        etudiant.getEmail(), etudiant.getTelNumber(), etudiant.getCycle(),
                        String.valueOf(etudiant.getNiveau())};
                    DefaultTableModel tblModel = (DefaultTableModel)tableEtudiant.getModel();

                    tblModel.addRow(tbData);
            }
            else if(cont instanceof Enseignant enseignant){
                String tbData[] = {cont.getCode(), cont.getNom(), cont.getDateDeNaissance().toString(), 
                    cont.getAdresse(), cont.getEmail(), cont.getTelNumber(),
                    enseignant.getStatut()};
                DefaultTableModel tblModel = (DefaultTableModel)tableEnseignant.getModel();

                tblModel.addRow(tbData);
            }else if(cont instanceof Agent agent){
                String tbData[] = {cont.getCode(), cont.getNom(), cont.getDateDeNaissance().toString(), 
                    cont.getAdresse(), cont.getEmail(), cont.getTelNumber(),
                    String.valueOf(agent.getSalaire()), agent.getStatut(),
                    agent.getCategorie(), agent.getIndiceDeSalaire(), agent.getOccupation()};
                DefaultTableModel tblModel = (DefaultTableModel)tableAgent.getModel();
            
                tblModel.addRow(tbData);
            }
        }
            
        this.choixComboBoxActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listeEtudiantPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEtudiant = new javax.swing.JTable();
        listeEnseignantPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEnseignant = new javax.swing.JTable();
        listeAgentPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableAgent = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        retour = new javax.swing.JButton();
        contentForm = new javax.swing.JPanel();
        choixComboBox = new javax.swing.JComboBox<>();

        tableEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Nom", "Date de naissance", "Adress", "Email", "Numéro Tel", "Cycle", "Niveaau"
            }
        ));
        jScrollPane2.setViewportView(tableEtudiant);
        if (tableEtudiant.getColumnModel().getColumnCount() > 0) {
            tableEtudiant.getColumnModel().getColumn(7).setHeaderValue("Niveaau");
        }

        javax.swing.GroupLayout listeEtudiantPanelLayout = new javax.swing.GroupLayout(listeEtudiantPanel);
        listeEtudiantPanel.setLayout(listeEtudiantPanelLayout);
        listeEtudiantPanelLayout.setHorizontalGroup(
            listeEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeEtudiantPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        listeEtudiantPanelLayout.setVerticalGroup(
            listeEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tableEnseignant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Nom", "Date de naissance", "Adress", "Email", "Numéro Tel", "Statut"
            }
        ));
        jScrollPane3.setViewportView(tableEnseignant);

        javax.swing.GroupLayout listeEnseignantPanelLayout = new javax.swing.GroupLayout(listeEnseignantPanel);
        listeEnseignantPanel.setLayout(listeEnseignantPanelLayout);
        listeEnseignantPanelLayout.setHorizontalGroup(
            listeEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        listeEnseignantPanelLayout.setVerticalGroup(
            listeEnseignantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        tableAgent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Nom", "Date de naissance", "Adress", "Email", "Numéro Tel", "Salaire", "Statut", "Categorie", "Indice de Salaire", "Occupation"
            }
        ));
        jScrollPane4.setViewportView(tableAgent);

        javax.swing.GroupLayout listeAgentPanelLayout = new javax.swing.GroupLayout(listeAgentPanel);
        listeAgentPanel.setLayout(listeAgentPanelLayout);
        listeAgentPanelLayout.setHorizontalGroup(
            listeAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(listeAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );
        listeAgentPanelLayout.setVerticalGroup(
            listeAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(listeAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listeAgentPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des Contatcs");

        retour.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentFormLayout = new javax.swing.GroupLayout(contentForm);
        contentForm.setLayout(contentFormLayout);
        contentFormLayout.setHorizontalGroup(
            contentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentFormLayout.setVerticalGroup(
            contentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        choixComboBox.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        choixComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Enseignant", "Agent" }));
        choixComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(590, Short.MAX_VALUE)
                .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(contentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(choixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixComboBoxActionPerformed
        int choix = choixComboBox.getSelectedIndex();
        
        if(choix == 0){
            contentForm.setLayout(new BorderLayout());
            contentForm.removeAll();
            contentForm.repaint();
            contentForm.add(this.listeEtudiantPanel);
            contentForm.revalidate();
        }
        else if(choix == 1){
            contentForm.setLayout(new BorderLayout());
            contentForm.removeAll();
            contentForm.repaint();
            contentForm.add(this.listeEnseignantPanel);
            contentForm.revalidate();
        }
        else if(choix == 2){
            contentForm.setLayout(new BorderLayout());
            contentForm.removeAll();
            contentForm.repaint();
            contentForm.add(this.listeAgentPanel);
            contentForm.revalidate();
        }
    }//GEN-LAST:event_choixComboBoxActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        this.parent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choixComboBox;
    private javax.swing.JPanel contentForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel listeAgentPanel;
    private javax.swing.JPanel listeEnseignantPanel;
    private javax.swing.JPanel listeEtudiantPanel;
    private javax.swing.JButton retour;
    private javax.swing.JTable tableAgent;
    private javax.swing.JTable tableEnseignant;
    private javax.swing.JTable tableEtudiant;
    // End of variables declaration//GEN-END:variables
}
